name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build Docker image
        run: docker build -t ahmadsaid/docker-react -f Dockerfile.dev .
      - name: Run tests
        run: docker run -e CI=true ahmadsaid/docker-react npm run test
      # - run: docker run ahmadsaid/docker-react npm run test -- --coverage